# Generated by Django 5.2 on 2025-04-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog_Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
